### PR TITLE
portable build.sh by using $HOME variable

### PR DESCRIPTION
**Pull request by aashoo17**
use $HOME variable
update build tools to version 30.0.3

### CODE REVIEW

**Comment by Synix** [comment]
Thanks for your PR!

What operation system do you use to build? I think "$HOME/Android/..." is operation system specific, because in my mac os path is "$HOME/Library/Android/...". So I think self-defined $ANDROID_HOME maybe better than $HOME. Do you think so?

Appreciate  if you could reply me.

**Comment by aashoo17** [comment]
Yes I am on Linux .
May be I will update the shell script to check for OS Linux/Mac and run conditional script based on it

**Comment by aashoo17** [comment]
You may reject the PR for time being

**Comment by aashoo17** [comment]
New modification will be created - as per discussion

**Pull request closed without merging**
